export const theme = {
  bg: '#f2f3f7',
  surface: '#ffffff',
  text: '#1a1a2e',
  text2: '#5b5d6b',
  text3: '#9597a6',
  border: '#ecedf2',
  shadow: '#d8dae3',
  primary: '#5b5fef',
  primaryLight: '#eeefff',
  success: '#2ed573',
  successBg: '#eafff2',
  warning: '#ffa502',
  warningBg: '#fff8ed',
  danger: '#ff4757',
  dangerBg: '#fff0f0',
  accent: '#ff6b81',
  radius: 12,
  radiusSm: 8,
  radiusLg: 16,
  shadowStyle: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
};
